FROM python:3.11.10-slim



ENV NAMU_DB_TYPE sqlite
ENV NAMU_DB data
ENV NAMU_HOST 0.0.0.0
ENV NAMU_PORT 3000
ENV NAMU_GOLANGPORT 3001
ENV NAMU_LANG en-US
ENV NAMU_MARKUP namumark
ENV NAMU_ENCRYPT sha3
ENV NAMU_DOCKER O

# PostgreSQL environment variables
ENV NAMU_POSTGRESQL_HOST localhost
ENV NAMU_POSTGRESQL_PORT 5432
ENV NAMU_POSTGRESQL_USER postgres
ENV NAMU_POSTGRESQL_PASSWORD password

ADD . /app
WORKDIR /app

RUN pip install -r requirements.txt
EXPOSE 3000

CMD [ "python", "./app.py" ]